### ISSUE TITLE
No Wire.beginTransmission() or Wire.endTransmission() needed for Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_IS31FL3731#2]
In the code is a bug, but if I tell what the bug is, this issue gets closed without explanation and without fixing the bug. Can someone from Adafruit help me out here ? All I want to do is to help Adafruit for free to make better code, because many use the Adafruit code as an example.

**Comment by microbuilder** [comment]
Hi Koepel ... we're aware of the bug, and it will be addressed, thanks. My suggestion was simply that rather than raising the same issue on so many Github repos, a pull request would be far more likely to solve the problem quickly.  Unfortunately, we have many hundreds of libraries to maintain and we can't always quickly deal with every request right away, which is why creating pull requests is far more helpful to everyone.

**Comment by Koepel** [comment]
Thank you for explaining. It is of course about this : https://github.com/adafruit/Adafruit_IS31FL3731/issues/1

I was thinking in a different direction: when the code will be updated some day, check the issues, and fix this issue as well.
Please keep an issue open until it is fixed.

**Comment by ladyada** [comment]
fixed
